services:
  # Container Oracle Database (Version Free - successeur de la XE, basée sur la 23c/23ai)
  oracle-db:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle_extensions_cours
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=MonPasswordSecurise123!
    volumes:
      - oracle_data:/opt/oracle/oradata

  # Container PostgreSQL (Dernière version majeure officielle)
  postgres-db:
    image: postgres:latest
    container_name: postgres_extensions_cours
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=prof_bd
      - POSTGRES_PASSWORD=MonPasswordPostgres123!
      - POSTGRES_DB=cours_objet
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Container pgAdmin 4
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_extensions_cours
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=prof@cours.fr
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=False
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres-db

volumes:
  oracle_data:
  postgres_data:
  pgadmin_data: